services:
  - type: web
    name: mybot
    env: python
    plan: free
    pythonVersion: 3.11.5
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python botone.py
    envVars:
      - key: BOT_TOKEN
        value: 8628986145:AAGMrNEKBZVhA9S-rlbhRUs7vkLqKj9Jiyc
      - key: GITHUB_TOKEN
        value: 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
      - key: REPO_OWNER
        value: Shine-lay-dotcom
      - key: REPO_NAME
        value: Mybot.py
      - key: ADMIN_ID
        value: 7074774446
      - key: BOT_PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.5
